[[codes]]
code = "kthft2020"
points = 200
valid_from = 2020-06-10T07:00:00+02:00
valid_to = 2020-06-11T00:00:00+02:00

[[quiz]]
name = "kthft"
points = 10

[[quiz.questions]]
question = "What food releases the least amount of CO₂ per gram of protein?"

correct = [
    "Maize",
]
incorrect = [
    "Chicken",
    "Pork",
    "Root vegetables",
]

[[quiz.questions]]
question = "What food uses the least amount of land (m²/year) per gram of of protein?"

correct = [
    "Tofu",
]
incorrect = [
    "Peas",
    "Farmed fish",
]
